keys:
  - &patchouli age1ah07pvg6fxt8smqv3mlcm45796jk2plummy8hu4mw5qt2d00ruxszlg6k9
  - &system_patchmini age1k3yjaw2qjs9y4a3t6z3q93hlj3qnw436wvvxnu9sq0x4y53gd3fq8gl534
  - &system_patchshell age168844yw9thh0n3g9g892su0p6fef76w2y3pdgsm247mvwxzza48qnlnzue

creation_rules:
  - path_regex: secrets\.yaml
    key_groups:
    - age:
      - *patchouli
      - *system_patchmini
      - *system_patchshell
